export let regions =  [
    {label:'上海市',id:'region1'},
    {label:'云南省',id:'region2'},
    {label:'内蒙古东部地区',id:'region3'},
    {label:'北京市',id:'region4'},
    {label:'吉林省',id:'region5'},
    {label:'四川省',id:'region6'},
    {label:'天津',id:'region7'},
    {label:'宁夏回族自治区',id:'region8'},
    {label:'安徽省',id:'region9'},
    {label:'山东省',id:'region10'},
    {label:'山西省',id:'region11'},
    {label:'广东省东西两翼地区',id:'region12'},
    {label:'广东省惠州市',id:'region13'},
    {label:'广东省江门市',id:'region14'},
    {label:'广东省珠三角五市',id:'region15'},
    {label:'广东省粤北山区',id:'region16'},
    {label:'广西壮族自治区',id:'region17'},
    {label:'新疆维吾尔自治区',id:'region18'},
    {label:'江苏省',id:'region19'},
    {label:'江西省',id:'region20'},
    {label:'河北省北部',id:'region21'},
    {label:'河北省南部',id:'region22'},
    {label:'河南省',id:'region23'},
    {label:'浙江省',id:'region24'},
    {label:'海南省',id:'region25'},
    {label:'湖北省',id:'region26'},
    {label:'湖南省',id:'region27'},
    {label:'甘肃省',id:'region28'},
    {label:'福建省',id:'region29'},
    {label:'贵州省',id:'region30'},
    {label:'辽宁省',id:'region31'},
    {label:'重庆市',id:'region32'},
    {label:'陕西省',id:'region33'},
    {label:'陕西省榆林地区',id:'region34'},
    {label:'青海省',id:'region35'},
    {label:'青海省(特殊行业)',id:'region36'},
    {label:'黑龙江省',id:'region37'},
]

export let vLevels = [
       {
        label:'不满1千伏',
        label:'1～10千伏',
        label:'1～10(20)千伏',// 山西
        label:'10千伏',
        label:'20千伏',
        label:'20~35千伏及以下',
        label:'35千伏',
        label:'35千伏及以上',
        label:'35千伏以下',
        label:'35~110千伏',
        label:'35~110千伏及以下',
        label:'66千伏',// 吉林
        label:'110千伏',
        label:'110千伏及以上',
        label:'110（66）千伏',// 辽宁
        label:'110千伏~220千伏及以下',
        label:'220千伏',
        label:'220千伏（330千伏）',
        label:'220千伏及以上',
        label:'330千伏及以上',
       }
]