export function getData(){ 
    
    return [
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 1,
        des: '储能柜日充电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 2,
        des: '储能柜日放电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 3,
        des: '电池单体温度',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 4,
        des: '电池单体电压',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 5,
        des: '电池堆电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 6,
        des: '电池堆电流',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 7,
        des: '电池堆电压',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 8,
        des: '电池堆循环次数',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 9,
        des: '电池堆健康度',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 10,
        des: '电池堆状态',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 11,
        des: '电池堆充电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 12,
        des: '池堆放电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 13,
        des: '电池堆实时报警',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 14,
        des: '单体温度最高',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 15,
        des: '单体温度最低',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 16,
        des: '单体温度平均',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 17,
        des: '单体电压最高',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 18,
        des: '单体电压最低',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 19,
        des: '单体电压平均',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 20,
        des: '电池堆充电功率',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 21,
        des: '电网电压',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 22,
        des: '电网电流',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 23,
        des: '交流有功功率',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 24,
        des: '交流无功功率',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 25,
        des: '功率因数',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 26,
        des: '模块温度',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 27,
        des: '直流功率',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 28,
        des: '直流电压',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 29,
        des: '直流电流',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 30,
        des: 'PCS运行状态',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 31,
        des: 'PCS充放电状态',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 32,
        des: 'PCS实时报警',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 33,
        des: '运行时长',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 34,
        des: '单柜累计充电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 35,
        des: '单柜累计放电量',
        dataVOList: [],
        dataDesListStr: '',
    },
    {
        orgId: '',
        projectId: '',
        lccuId: '',
        deviceId: '',
        deviceName: '',
        statisticsType: 37,
        des: '电池堆放电功率',
        dataVOList: [],
        dataDesListStr: '',
    },
]}